services:
  aerospike:
    image: aerospike/aerospike-server:latest
    container_name: aerospike-workshop
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    volumes:
      - ./config/aerospike/aerospike.conf:/etc/aerospike/aerospike.conf
      - aerospike-data:/opt/aerospike/data
    healthcheck:
      test: ["CMD", "asinfo", "-p", "3000", "-v", "status"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  aerospike-data:
