
# Aerospike database configuration file
# This template sets up a single-node, single namespace developer environment.
#
# Alternatively, you can pass in your own configuration file.
# You can see more examples at
# https://github.com/aerospike/aerospike-server/tree/master/as/etc

# This stanza must come first.
service {
	
	cluster-name docker
	node-id-interface eth0
}

logging {
	
	
	
	

	# Send log messages to stdout
	console {
		context any info
	}
}

network {
	service {
		address eth0
		port 3000
		access-address 127.0.0.1
	}

	heartbeat {
		# mesh is used for environments that do not support multicast
		mode mesh
		port 3002
		interval 150
		timeout 10
	}

	fabric {
		# Intra-cluster communication port (migrates, replication, etc)
		port 3001
	}

}

namespace test {
	replication-factor 1
	
	nsup-period 120

	storage-engine device {
		# For 'storage-engine memory' with 'device' or 'file' backing, we
		# recommend having multiple devices (eight is recommended). One is used
		# here for backward compatibility.
		file /opt/aerospike/data/test.dat
		filesize 4G
		read-page-cache true
	}
}
